apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
	name: terraform
	namespace: flux-system
spec:
	interval: 10m
	sourceRef:
		kind: GitRepository
		name : terraform-repo
	path : ./