apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: terraform
spec:
  interval: 10m
  sourceRef:
   kind: GitRepository
   name : terraform-app
  path : ./terraform
  prune: true

---
apiVersion: infra.contrib.fluxcd.io/v1alpha1
kind: Terraform
metadata:
  name: terraform-nginx
spec:
  path: ./terraform
  approvePlan: ""
  interval: 1m
  sourceRef:
    kind: GitRepository
    name: terraform-app