apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: terraform
  namespace: flux-system
spec:
  interval: 10m
  sourceRef:
   kind: GitRepository
   name : terraform-app
  path : ./terraform
  prune: true